### ISSUE TITLE
Feature: LoggerAwareTrait should use full-qualified class name for interface

### ISSUE THREAD

**Issue by maikgreubel** [php-fig/log#34]
Either a use statement or full-qualified class name for interface or property should be part of the doc comment.
Original:

```php
namespace Psr\Log;

/**
 * Basic Implementation of LoggerAwareInterface.
 */
trait LoggerAwareTrait
{
    /** @var LoggerInterface */
    protected $logger;
```

Should be:

```php
namespace Psr\Log;

// either
// use \Psr\Log\LoggerInterface;
/**
 * Basic Implementation of LoggerAwareInterface.
 */
trait LoggerAwareTrait
{
    // or
    /** @var \Psr\Log\LoggerInterface */
    protected $logger;
```

Just to support autocompletion in IDE.

**Comment by mnapoli** [comment]
:-1: autocompletion works fine, `LoggerInterface` is a valid identifier in the file because it is in the same namespace.

**Comment by maikgreubel** [comment]
Well, it works if I import the LoggerInterface into my class via use-statement. But If it is not imported, IDE (Eclipse + PDT by the way) assumes LoggerInterface is same namespace of class where I included the trait. Because of LoggerInterface exists not as class or interface in same namespace scope of my class, IDE does not provide an autocompletion.

Example, which does not work as expected:

```php
namespace My\Namespace;

use \Psr\Log\LoggerAwareTrait;

class MyClass
{
  use LoggerAwareTrait;

  public function superDuperFunction()
  {
    $this->logger-> // << here no autocompletion support
  }
}
``` 

And the example, where it works:

```php
namespace My\Namespace;

use \Psr\Log\LoggerAwareTrait;
use \Psr\Log\LoggerInterface;

class MyClass
{
  use LoggerAwareTrait;

  public function superDuperFunction()
  {
    $this->logger-> // << here autocompletion provided
  }
}
```

From my users point of view I should not import classes or interfaces which I don't care of. I just want to import LoggerAwareTrait. What the trait internally makes use of is not scope of my development.

Another point: What about the LoggerInterface if I have one class in the same namespace than my class?

Just my opinion.

Regards

**Comment by mnapoli** [comment]
> it works if I import the LoggerInterface into my class via use-statement.

Exactly, and in the file you are suggesting the modification this is exactly the case. There is no need to use the FQN here.

If you have problems with autocompletion in *your* files it's either because your IDE is not smart enough, or because you are using the interface without importing it.

To illustrate my point, if there was a type-hint in the trait (i.e. in this file here) it would run perfectly well without errors using `LoggerInterface` (not FQN).

**Comment by maikgreubel** [comment]
> Exactly, and in the file you are suggesting the modification this is exactly the case.

Sorry, but which file do you mean? In https://github.com/php-fig/log/blob/master/Psr/Log/LoggerAwareTrait.php is no use-import for LoggerInterface. Neither for master nor tag "1.0.0".

**Comment by mnapoli** [comment]
There is no import because they are in the same namespace: LoggerAwareTrait is in the same namespace as LoggerInterface, so there is no need for importing it.
