### ISSUE TITLE
Phpunit dependency

### ISSUE THREAD

**Issue by yosmanyga** [php-fig/log#40]
`LoggerInterfaceTest` extends `\PHPUnit_Framework_TestCase` but there is no phpunit dependency in composer.json.

**Comment by Seldaek** [comment]
I don't think we want to force every project using the interfaces to install phpunit, that just wouldn't be reasonable. It's only applicable to implementor projects that also want to test their code with phpunit, so I think it's ok as is really.

**Comment by snapshotpl** [comment]
@Seldaek what about `require-dev`?

**Comment by Seldaek** [comment]
That wouldn't help though?

**Comment by snapshotpl** [comment]
As I know, when you define `require-dev` they install only when updated directly on this `composer.json`.

**Comment by yosmanyga** [comment]
I'm using a library that parses the docblock classes with ReflectionClass and it breaks on this class because of this. So it means that I should know that it requires phpunit and add it manually. But that's composer's job.

What about moving this class to a different library, something like `log-phpunit`?

**Comment by Seldaek** [comment]
Well lots of packages have optional dependencies so I doubt that'll really help.. Yes we could/should move it to an external package I guess but that'd be a BC break strictly speaking.

**Comment by yosmanyga** [comment]
Yeah it's true. The same happens with lot of libraries. Ok, I guess I should add some ignored list based on namespace. Thanks for your help.
